#!/bin/bash

# Install emulation
apt-get update
apt-get install qemu-user-static -y

echo "Currently in directory:"
pwd

# Copy to build context
cp /usr/bin/qemu-arm-static .

# Register QEMU in build agent
docker run --rm --privileged multiarch/qemu-user-static:register --reset
